name: Publish packages

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: git config email
        run: git config --local user.email "97040625+BotDucky@users.noreply.github.com"
      - name: git config name
        run: git config --local user.name BotDucky

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush Rebuild
        run: node common/scripts/install-run-rush.js rebuild

      - name: Rush Publish
        run: node common/scripts/install-run-rush.js publish --publish --apply --target-branch main
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
