# Publish packages to NPM using RushJS
name: Publish packages

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Fetch repo with entire git history
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.1'
      # Set up GitHub user to https://github.com/BotDucky
      - name: git config email
        run: git config --local user.email "97040625+BotDucky@users.noreply.github.com"
      - name: git config name
        run: git config --local user.name BotDucky

      # Make sure Change logs are properly documented
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      # Install all dependencies
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      # Build all projects
      - name: Rush Rebuild
        run: node common/scripts/install-run-rush.js rebuild

      # Publish packages, delete temporary change logs files, commit and push updated change logs
      - name: Rush Publish
        run: node common/scripts/install-run-rush.js publish --publish --apply --target-branch main
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Build Storybook
      - name: Storybook build
        run: rush build-storybook --from @ducky/plumage

      # Publish Storybook
      - name: Storybook Publish
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.STORYBOOK_GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.STORYBOOK_GCP_APPLICATION_CREDENTIALS }}
        with:
          args: -h "Cache-Control:public, max-age=3600" cp -r ./storybook-static/* gs://components.ducky.eco
          cli: gsutil

      # Storybook: Set max-age on index.html to 5 minutes
      - name: Storybook Publish
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.STORYBOOK_GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.STORYBOOK_GCP_APPLICATION_CREDENTIALS }}
        with:
          args: setmeta -h "Cache-Control:public, max-age=300" gs://components.ducky.eco/index.html
          cli: gsutil
