# A set of checks to run on each PR: changelogs, build, all kind of tests
name: PR checks

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Check presence of changelog documentation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

  builds:
    runs-on: ubuntu-latest
    name: Check build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush Rebuild
        run: node common/scripts/install-run-rush.js rebuild
      - name: Storybook build
        run: node common/scripts/install-run-rush.js build-storybook --from @ducky/plumage
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush Rebuild
        run: node common/scripts/install-run-rush.js rebuild
      - name: Tests
        run: node common/scripts/install-run-rush.js test
